spring:
  datasource:
    url: jdbc:postgresql://dpg-copeh84f7o1s73dujvmg-a.ohio-postgres.render.com:5432/flowers_jkia
    username: flowers_jkia_user
    password: x90MotJD8Tx0zJNPJxG9TDLaQbQBXcUi

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always